spring.application.name=LabManager

# H2 Database for development (switch to MySQL later)
#spring.datasource.url=jdbc:h2:mem:labmanagerdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require&pgbouncer=true&prepareThreshold=0
spring.datasource.username=postgres.emwzipkyxymoegwbipoc
spring.datasource.password=Tujefa789456.
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Supavisor (PgBouncer) Connection Pooling Fixes
spring.datasource.hikari.auto-commit=false
spring.jpa.properties.hibernate.connection.provider_disables_autocommit=true
spring.jpa.properties.hibernate.jdbc.time_zone=America/Mexico_City

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.encoding=UTF-8

# --- Email Configuration (Resend over SSL to bypass Render blocks) ---
spring.mail.host=smtp.resend.com
spring.mail.port=465
spring.mail.username=resend
# NOTE: This is a temporary testing key for Resend. 
spring.mail.password=re_UfQyD1YJ_2kKjXo2W4bX3rWz9yL9kP8mN
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false



# JWT Secret (Move to env var in production)
labmanager.app.jwtSecret=SecretKeyToGenJWTsShouldBeLongAndComplexAndStoredSecurely
labmanager.app.jwtExpirationMs=3600000

# File Upload Limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
